apiVersion: v1
kind: Endpoints
metadata:
  creationTimestamp: null
  labels:
    datasource: oracle
  name: oracle
subsets:
- addresses:
  - ip: 172.23.198.17
  - ip: 172.23.198.18
  - ip: 172.23.198.19
  ports:
  - name: oracle
    port: 1521
    protocol: TCP
