apiVersion: v1
kind: Service
metadata:
  annotations:
    description: Oracle Datasource
  creationTimestamp: null
  labels:
    datasource: oracle
  name: oracle
spec:
  ports:
  - name: oracle
    port: 1521
    protocol: TCP
    targetPort: 1521
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
